version: '2.4'

services:

  proxy:
    extends:
      file: base.yml
      service: proxy
    volumes: ["../../:/app"]
    environment:
      DHOST_IP: ${DHOST_IP}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  queue:
    extends:
      file: base.yml
      service: queue
    volumes: ["../../:/app"]
    environment:
      DHOST_IP: ${DHOST_IP}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  redis:
    extends:
      file: base.yml
      service: redis
    ports:
      - "6379:6379"

  prerenderer:
    extends:
      file: base.yml
      service: prerenderer
    ports:
      - "3000:3000"

  rabbit:
    extends:
      file: base.yml
      service: rabbit
    ports:
      - "15672:15672"
    volumes:
      - ../rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
