version: '2.4'

services:
  proxy:
    extends:
      file: base.yml
      service: proxy
    volumes: ["../../:/app"]

  queue:
    extends:
      file: base.yml
      service: queue
    volumes: ["../../:/app"]

  idilic:
    extends:
      file: base.yml
      service: idilic
    volumes: ["../../:/app"]

  redis:
    extends:
      file: base.yml
      service: redis

  prerenderer:
    extends:
      file: base.yml
      service: prerenderer

  rabbit:
    extends:
      file: base.yml
      service: rabbit
    ports:
      - "15672:15672"
    volumes:
      - ../rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
